### ISSUE TITLE
Key mappings

### ISSUE THREAD

**Issue by akemrir** [brookhong/jdb.vim#1]
Hi, how can I customize key mappings?
Or simply disable them and make custom key map.

They are interfering with my key map right now.
I would like to move them to some prefix like <leader>d, or something similar.

I like this addon and I want make use of it ;)

**Comment by akemrir** [comment]
Hi, I've prepared changes locally. Could you give me permission and I will prepare PR?

**Comment by brookhong** [comment]
PR needs no permission, just send out your PR, then I can review and merge it.

**Comment by akemrir** [comment]
Hi, could you review PR?

**Comment by brookhong** [comment]
thanks, merged.
